/* DROP 테이블 */
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE CTA_CHARGE CASCADE CONSTRAINTS;
DROP TABLE CTA CASCADE CONSTRAINTS;
DROP TABLE MYPOINT CASCADE CONSTRAINTS;
DROP TABLE POINT CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
DROP TABLE REVIEW_COMMENT CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE QNA_COMMENT CASCADE CONSTRAINTS;
DROP TABLE QNA_BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL_IMAGE CASCADE CONSTRAINTS;
DROP TABLE HOS_PAY CASCADE CONSTRAINTS;
DROP TABLE HOS_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_TYPE CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL CASCADE CONSTRAINTS;
DROP TABLE HAIR_SALON_IMG CASCADE CONSTRAINTS;
DROP TABLE HAR_PAY CASCADE CONSTRAINTS;
DROP TABLE HAR_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE STYLE CASCADE CONSTRAINTS;
DROP TABLE HAIR_SALON CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE PET_INFO CASCADE CONSTRAINTS;
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
DROP TABLE CHATMESSAGE CASCADE CONSTRAINTS;
DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_PARTNER CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;
DROP TABLE OFTEN_QNA;

DROP SEQUENCE SEQ_BUSINESS_PARTNER;
DROP SEQUENCE SEQ_CLIENT;
DROP SEQUENCE SEQ_ANNOUNCEMENT;
DROP SEQUENCE SEQ_QNA_BOARD;
DROP SEQUENCE SEQ_QNA_COMMENT;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_REVIEW_COMMENT;
DROP SEQUENCE SEQ_BOARD;
DROP SEQUENCE SEQ_BOARD_COMMENT;
DROP SEQUENCE SEQ_CHAT_ROOMID;
DROP SEQUENCE SEQ_CHAT_MESSAGE;
DROP SEQUENCE SEQ_NOTICE;
DROP SEQUENCE SEQ_POINT;
DROP SEQUENCE SEQ_CTA;
DROP SEQUENCE SEQ_CTA_CHARGE;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_PET_INFO;
DROP SEQUENCE SEQ_HAIR_SALON;
DROP SEQUENCE SEQ_HAR_RESERVATION;
DROP SEQUENCE SEQ_HAR_PAY;
DROP SEQUENCE SEQ_LIKES;
DROP SEQUENCE SEQ_STYLE;
DROP SEQUENCE SEQ_HOSPITAL;
DROP SEQUENCE SEQ_HOS_RESERVATION;
DROP SEQUENCE SEQ_ SEQ_HOS_PAY;
DROP SEQUENCE SEQ_MEDICAL_TYPE;
DROP SEQUENCE SEQ_OFTEN_QNA;

--------------------------------------------------------------------------------------------------

/* SEQUENCE */
CREATE SEQUENCE SEQ_BUSINESS_PARTNER
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CLIENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_ANNOUNCEMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_QNA_BOARD
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_QNA_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_REVIEW
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_BOARD
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_BOARD_COMMENT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CHAT_ROOMID
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;
    
CREATE SEQUENCE SEQ_CHAT_MESSAGE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_NOTICE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_POINT
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CTA
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_CTA_CHARGE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_LIKES
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_PET_INFO
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAIR_SALON
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAR_RESERVATION
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HAR_PAY
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_LIKES
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_STYLE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOSPITAL
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOS_RESERVATION
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_HOS_PAY
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_MEDICAL_TYPE
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_OFTEN_QNA
    INCREMENT BY 1 
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;
-----------------------------------------------------------------------------------------------

/* ADMIN 테이블 */
CREATE TABLE ADMIN( 
    ADMIN_ID VARCHAR2(50) CONSTRAINT MANAGER_MEG_EMAIL_PK PRIMARY KEY,
    ADMIN_PWD VARCHAR2(30) NOT NULL 
);


/* BUSINESS_PARTNER 테이블 */
CREATE TABLE BUSINESS_PARTNER ( 
    BP_ID VARCHAR2(20) CONSTRAINT BUSINESS_PARTNER_BP_ID_PK PRIMARY KEY, 
    BP_PWD VARCHAR2(30) NOT NULL, 
    BP_NAME VARCHAR2(20) NOT NULL, 
    BP_TEL VARCHAR2(20) NOT NULL UNIQUE, 
    BP_BANK VARCHAR2(20) NULL, 
    BP_ACNT VARCHAR2(20) NULL , 
    BP_EMAIL VARCHAR2(20) NOT NULL UNIQUE,
    BP_NUM VARCHAR2(20) NOT NULL,
    BP_TYPE NUMBER(1) NOT NULL,
    BP_APRVE NUMBER(1) DEFAULT 0 NOT NULL
    BP_DELETE NUMBER(1) DEFAULT 0 NOT NULL,
    BP_REG NUMBER(1) DEFAULT 0,
    REG_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMM')
);

/* CLIENT 테이블 */
CREATE TABLE CLIENT (
    CL_NUM VARCHAR2(20) CONSTRAINT CLIENT_CL_NUM_PK PRIMARY KEY,
    CL_EMAIL VARCHAR2(20) NOT NULL UNIQUE,
    CL_PWD VARCHAR2(30) NOT NULL,
    CL_NICKNAME VARCHAR2(20) NOT NULL,
    CL_NAME VARCHAR2(20) NOT NULL,
    CL_TEL VARCHAR2(20) NOT NULL UNIQUE,
    NAVERLOGIN VARCHAR2(30 BYTE),
    KAKAOLOGIN VARCHAR2(30 BYTE),
REG_DATE VARCHAR2(20 BYTE) DEFAULT TO_CHAR(SYSDATE, 'YYYYMM')
);


/* PET_INFO 테이블 */
CREATE TABLE PET_INFO (
    PET_NUM VARCHAR2(20) CONSTRAINT PET_INFO_PET_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT PET_INFO_CL_NUM_FK REFERENCES CLIENT,
    PET_NAME VARCHAR2(100) NOT NULL,
    PET_KIND VARCHAR2(20) NOT NULL,
    PET_BIRTH VARCHAR2(20) NOT NULL,
    PET_GEN VARCHAR2(20) NOT NULL,
    PET_NEUT NUMBER(2),
    PET_EXPER VARCHAR2(20),
    PET_VACCIN VARCHAR2(20),
    PET_BITE VARCHAR2(20),
    KNEECAP VARCHAR2(10),
    DISLIKE VARCHAR2(20),
    PET_OTHERS VARCHAR2(20),
    PET_IMG VARCHAR2(2000),
    MBTI VARCHAR2(20),
    PET_WEIGHT VARCHAR2(20)
);


/* NOTICE 테이블 */
CREATE TABLE NOTICE (
    NOTICE_NUM VARCHAR2(20) PRIMARY KEY,
    NOTICE_CONTENT VARCHAR(20),
    NOTICE_RECEIVER VARCHAR2(20),
    NOTICE_PUBLISHER VARCHAR2(20),
    REFERENCE_NUM VARCHAR2(60),
    REFERENCE_CLASS VARCHAR2(20),
    READ_STATE NUMBER(1),
    NOTICE_TIME VARCHAR2(20)
);


/* HAIR_SALON 테이블 */
CREATE TABLE HAIR_SALON (
    HAR_NUM VARCHAR2(20) CONSTRAINT HAIR_SALON_HAR_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT HAIR_SALON_BP_ID_FK REFERENCES BUSINESS_PARTNER NOT NULL,
    HAR_ADDR VARCHAR2(300) NOT NULL,
 HAR_TEL VARCHAR2(20) NOT NULL,
HOPEN_TIME VARCHAR2(100),
HAR_MINFO VARCHAR2(500),
HAR_NAME VARCHAR2(20),
HAR_MIMG VARCHAR2(500)
);


/* STYLE 테이블 */
CREATE TABLE STYLE (
    STYLE_NUM VARCHAR2(20) CONSTRAINT STYLE_STYLE_NUM_PK PRIMARY KEY,
    HAR_NUM VARCHAR2(20) CONSTRAINT STYLE_HAR_NUM_FK REFERENCES HAIR_SALON
    NOT NULL,
    STYLE_NAME VARCHAR2(200) NOT NULL,
    PRICE NUMBER(7) NOT NULL,
    STYLE_TIME NUMBER(3),
    STYLE_DEEP NUMBER(1) DEFAULT 0 NOT NULL,
    STYE_NUM2 VARCHAR2(20)
);


/* HAR_RESERVATION 테이블 */
CREATE TABLE HAR_RESERVATION (
    HAR_RNUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_HAR_RNUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_CL_NUM_FK REFERENCES CLIENT
    NOT NULL,
    PET_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_PET_NUM_FK REFERENCES     
    PET_INFO NOT NULL,
    STYLE_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_STYLE_NUM_FK REFERENCES 
    STYLE NOT NULL,
    HAR_NUM VARCHAR2(20) CONSTRAINT HAR_RESERVATION_HAR_NUM_FK REFERENCES 
    HAIR_SALON NOT NULL,
    RES_DATE VARCHAR2(50) NOT NULL,
    STYLE_NUM2 VARCHAR2(20),
    RES_STATUS VARCHAR2(20),
    RES_TIME VARCHAR2(30) NOT NULL,
    RES_CHK NUMBER(1) NOT NULL DEFAULT 0
);


/* HAR_PAY 테이블 */
CREATE TABLE HAR_PAY (
    PAY_NUM VARCHAR2(50) CONSTRAINT HAR_PAY_PAY_NUM_PK PRIMARY KEY,
    HAR_RNUM VARCHAR2(20) CONSTRAINT HAR_PAY_HAR_RNUM_FK REFERENCES HAR_RESERVATION
    NOT NULL,
    CARD_NUM VARCHAR2(50) NOT NULL,
    PAY_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD') NOT NULL,
    PAY_PRICE NUMBER(7) NOT NULL,
    TOTAL_PRICE NUMBER(7) NOT NULL
);


/* HAIR_SALON_IMG 테이블 */
CREATE TABLE HAIR_SALON_IMG (
   IMG_NUM VARCHAR2(20) CONSTRAINT HAIR_SALON_IMG_NUM_PK PRIMARY KEY,
   HAR_NUM VARCHAR2(20) CONSTRAINT HAIR_SALON_IMG_HAR_NUM_FK REFERENCES 
    HAIR_SALON,
    HAR_IMG VARCHAR2(500)
);

/* HOSPITAL 테이블 */
CREATE TABLE HOSPITAL (
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_HOS_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT HOSPITAL_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    HOS_ADDR VARCHAR2(300) NOT NULL,
    HOS_TEL VARCHAR2(20) NOT NULL,
    OPEN_TIME VARCHAR2(20),
    HOS_MINFO VARCHAR2(500),
    HOS_NAME VARCHAR2(100),
    HOS_MIMG VARCHAR2(500)
);


/* MEDICAL_TYPE 테이블 */
CREATE TABLE MEDICAL_TYPE (
    MED_NUM VARCHAR2(20) CONSTRAINT MEDICAL_TYPE_MED_NUM_PK PRIMARY KEY,
    MED_NAME VARCHAR2(500) NOT NULL,
    MED_PRICE NUMBER(7) NOT NULL,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_HOS_NUM _FK REFERENCES HOSPITAL NOT NULL
);


/* HOS_RESERVATION 테이블 */
CREATE TABLE HOS_RESERVATION (
    HOS_RNUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_HOS_RNUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_CL_NUM_FK REFERENCES CLIENT
    NOT NULL,
    PET_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_PET_NUM_FK REFERENCES     
    PET_INFO NOT NULL,
    MED_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_MED_NUM_FK REFERENCES 
    MEDICAL_TYPE NOT NULL,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOS_RESERVATION_HOS_NUM_FK REFERENCES 
    HOSPITAL NOT NULL,
    HOS_DATE VARCHAR2(50) NOT NULL,
    MED_NUM2 VARCHAR2(20),
    HOS_STATUS NUMBER(1) NOT NULL,
    HOS_TIME VARCHAR2(30) NOT NULL,
    RES_CHK NUMBER(1) NOT NULL
);



/* HOS_PAY 테이블 */
CREATE TABLE HOS_PAY (
    PAY_NUM VARCHAR2(20) CONSTRAINT HOS_PAY_PAY_NUM_PK PRIMARY KEY,
    HOS_RNUM VARCHAR2(20) CONSTRAINT HOS_PAY_HOS_RNUM_FK REFERENCES HOS_RESERVATION NOT NULL,
    CARD_NUM VARCHAR2(20),
    PAY_DATE VARCHAR2(20) NOT NULL,
    PAY_PRICE NUMBER(7) NOT NULL,
    TOTAL_PRICE NUMBER(7)
);



/* HOSPITAL_IMAGE 테이블 */
CREATE TABLE HOSPITAL_IMAGE (
IMG_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_IMG_NUM_PK PRIMARY KEY,
    HOS_NUM VARCHAR2(20) CONSTRAINT HOSPITAL_IMAGE_HOS_NUM_FK REFERENCES HOSPITAL,
    HOS_IMG VARCHAR2(500)
);


/* BOARD 테이블 */
CREATE TABLE BOARD ( 
    BO_NUM VARCHAR2(20) CONSTRAINT BOARD_BO_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) NOT NULL CONSTRAINT BOARD_CL_NUM_FK REFERENCES CLIENT,
    CL_NICKNAME VARCHAR2(20) NOT NULL,
    BO_TITLE VARCHAR2(100) NOT NULL,
    BO_CONT VARCHAR2(3000) NOT NULL,
    BO_IMG VARCHAR2(200),
    BO_DATE VARCHAR2(20) DEFAULT SYSDATE NOT NULL,
    BO_VIEW NUMBER(10) DEFAULT 0 NOT NULL,
    BOC_CHK NUMBER(5) NOT NULL
);


/* B_COMMENT 테이블 */
CREATE TABLE BOARD_COMMENT ( 
    CO_NUM VARCHAR2(20) CONSTRAINT BOARD_COMMENT_CO_NUM_PK PRIMARY KEY,
    BO_NUM VARCHAR2(20) NOT NULL CONSTRAINT BOARD_COMMENT_CO_NUM_BO_NUM_FK REFERENCES BOARD,
    CL_NUM VARCHAR2(20) NOT NULL CONSTRAINT BOARD_COMMENT_CL_NUM_FK REFERENCES CLIENT,
    CL_NICKNAME VARCHAR2(20) NOT NULL,
    CO_CONT VARCHAR2(1000) NOT NULL,
    CO_DATE VARCHAR2(20) NOT NULL
);


/* QNA_BOARD 테이블 */
CREATE TABLE QNA_BOARD ( 
    QNA_NUM VARCHAR2(10) CONSTRAINT QNA_BOARD_QNA_NUM_PK PRIMARY KEY,
    USER_NUM VARCHAR2(20) NOT NULL,
    QNA_TITLE VARCHAR2(100) NOT NULL,
    QNA_CONT VARCHAR2(3000) NOT NULL,
    QNA_IMG VARCHAR2(200),
QNA_DATE VARCHAR2(20) NOT NULL,
    QNA_WR VARCHAR2(50) NOT NULL,
QNA_TYPE NUMBER(1) NOT NULL,
    QNAR_CHK NUMBER(1) DEFAULT 0
);


/* QNA_COMMENT 테이블 */
CREATE TABLE QNA_COMMENT ( 
    QNAC_NUM VARCHAR2(10) CONSTRAINT QNAC_COMMENT_QNAR_NUM_PK PRIMARY KEY, 
    ADMIN_ID VARCHAR2(50) CONSTRAINT QNA_COMMENT_ADMIN_ID_FK REFERENCES MESSAGE, 
    QNA_NUM VARCHAR2(50) CONSTRAINT QNA_COMMENT_QNA_NUM_FK REFERENCES QNA_BOARD, 
    QNAC_CONT VARCHAR2(1000), 
    QNAC_DATE VARCHAR2(20) 
);


/* REVIEW 테이블 */
CREATE TABLE REVIEW (
    REV_NUM VARCHAR2(20) CONSTRAINT REVIEW_REV_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(20) CONSTRAINT REVIEW_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    CL_NUM VARCHAR2(20) CONSTRAINT REVIEW_CL_NUM_FK REFERENCES CLIENT,
CL_NICKNAME VARCHAR2(20) NOT NULL,
REV_CONT VARCHAR2(3000),
    REV_IMG VARCHAR2(200),
    REV_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD') NOT NULL,
    REV_VAL NUMBER(5) NOT NULL,
    CMNT_CHK NUMBER(1) NOT NULL
);


/* REVIEW_COMMENT 테이블 */
CREATE TABLE REVIEW_COMMENT (
    REVC_NUM VARCHAR2(10) CONSTRAINT REVIEW_COMMENT_REVR_NUM_PK PRIMARY KEY,
    BP_ID VARCHAR2(50) CONSTRAINT REVIEW_COMMENT_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    REV_NUM VARCHAR2(10) CONSTRAINT REVIEW_COMMENT_REV_NUM_FK REFERENCES REVIEW,
    REVC_CONT VARCHAR2(1000) NOT NULL,
    REVC_DATE VARCHAR2(20) NOT NULL
);


/* ANNOUNCEMENT 테이블 */
CREATE TABLE ANNOUNCEMENT ( 
    ANN_NUM VARCHAR2(10) CONSTRAINT ANNOUNCEMENT_ANN_NUM_PK PRIMARY KEY, 
    ADMIN_ID VARCHAR2(50) CONSTRAINT ANNOUNCEMEN_ADMIN_ID_FK REFERENCES MESSAGE, 
    ANN_TITLE VARCHAR2(100) NOT NULL,
ANN_CONT VARCHAR2(3000) NOT NULL,
    ANN_DATE VARCHAR2(20) NOT NULL, 
    ANN_VIEW NUMBER(1) DEFAULT 0
);


/* CHATROOM 테이블 */
CREATE TABLE CHATROOM (
    CHATROOM_ID VARCHAR2(20) CONSTRAINT CHATROOM_CHATROOM_ID_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT CHATROOM_CL_NUM_FK REFERENCES CLIENT,
    BP_ID VARCHAR2(50) CONSTRAINT CHATROOM_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    BP_TYPE NUMBER(1)
);


/* CHATMESSAGE 테이블 */
CREATE TABLE CHATMESSAGE (
    MESSAGE_ID VARCHAR2(20) CONSTRAINT CHATMESSAGE_MESSAGE_ID_PK PRIMARY KEY,
    MESSAGE_SENDER VARCHAR(20),
    MESSAGE_RECEIVER VARCHAR(20),
    MESSAGE_CONTENT VARCHAR(2000),
    MESSAGE_SENDTIME TIMESTAMP,
    CHATROOM_ID CONSTRAINT CHATMESSAGE_CHATROOM_ID_FK REFERENCES CHATROOM,
    UNREAD_COUNT NUMBER(1),
    INVISIBLE_CLIENT NUMBER(1),
    INVISIBLE_BP NUMBER(1),
);


/* POINT 테이블 */
CREATE TABLE POINT ( 
    POINT_NUM VARCHAR2(20) CONSTRAINT POINT_POINT_NUM_PK PRIMARY KEY, 
    POINT_NAME VARCHAR2(20) NOT NULL, 
    EXP_TYPE VARCHAR2(20) NOT NULL,
    SCORE NUMBER(7) NOT NULL
);


/* MYPOINT 테이블 */
CREATE TABLE MYPOINT (
 CL_NUM VARCHAR2(50) CONSTRAINT MYPOINT_CL_NUM_FK REFERENCES CLIENT,
    POINT_NUM VARCHAR2(20) CONSTRAINT MYPOINT_POINT_NUM_FK REFERENCES POINT,
    INDEXS NUMBER(5), 
    EXP_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),  
 EXP_TYPE VARCHAR2(20),
 EXP_FROM VARCHAR2(50),
 EXP_ID VARCHAR2(20),
 EXP_POINT NUMBER(5) DEFAULT 0,
 CURR_POINT NUMBER(7) DEFAULT 0  
);


/* CTA테이블 */
CREATE TABLE CTA ( 
    CHRG_NUM VARCHAR2(20) CONSTRAINT MYPOINT_POINT_NUM_FK REFERENCES POINT, 
CM_CODE VARCHAR2(20) CONSTRAINT CTA_CM_CODE_PK PRIMARY KEY,
    CM_TYPE NUMBER(10) NOT NULL,
    PRICE NUMBER(7) NOT NULL
);


/* CTA_CHARGE테이블 */
CREATE TABLE CTA_CHARGE ( 
    CHRG_NUM VARCHAR2(20) CONSTRAINT CTA_CHARGE_CHRG_NUM_PK PRIMARY KEY,
    CM_CODE VARCHAR2(20) NOT NULL CONSTRAINT CTA_CHARGE_CM_CODE_FK REFERENCES CTA,
    BP_ID VARCHAR2(50) CONSTRAINT CTA_CHARGE_BP_ID_FK REFERENCES BUSINESS_PARTNER,
    CHRG_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD') NOT NULL
);


/* LIKE 테이블 */
CREATE TABLE LIKES (
    LIKE_NUM VARCHAR2(20) CONSTRAINT LIKES_LIKE_NUM_PK PRIMARY KEY,
    CL_NUM VARCHAR2(20) CONSTRAINT LIKES_CL_NUM_FK REFERENCES CLIENT,
    HAR_NUM VARCHAR2(20) CONSTRAINT LIKES_HAR_NUM_FK REFERENCES HAIR_SALON,
    HOS_NUM VARCHAR2(20) CONSTRAINT LIKES_HOS_NUM_FK REFERENCES HOSPITAL
);

/*USUAL_QNA 테이블*/
CREATE TABLE OFTEN_QNA (
    OF_NUM VARCHAR2(20) CONSTRAINT OF_NUM_PK PRIMARY KEY, 
    OF_TITLE VARCHAR2(50) NOT NULL,
    OF_CONT VARCHAR2(3000) NOT NULL,
    OF_TYPE NUMBER(1) NOT NULL
);

--INSERT TEMPORARY ADMIN
INSERT INTO ADMIN VALUES('admin',’admin’);

COMMIT;




-- procedure
create or replace PROCEDURE HAR_RESERVATION_DATE
IS
    ARG_RES_STATUS NUMBER;
BEGIN
 
    FOR i IN (SELECT RES_STATUS FROM HAR_RESERVATION ) LOOP
    
    ARG_RES_STATUS := i.res_status;   
    
    IF ARG_RES_STATUS = 0 THEN
         UPDATE HAR_RESERVATION SET RES_STATUS = 3 WHERE RES_DATE < SYSDATE AND ARG_RES_STATUS = 0;
    ELSIF ARG_RES_STATUS = 1 THEN 
     UPDATE HAR_RESERVATION SET RES_STATUS = 2 WHERE RES_DATE < SYSDATE AND ARG_RES_STATUS = 1;
    END IF; 
    
    END LOOP;
    
    COMMIT;
END;

create or replace PROCEDURE HOS_RESERVATION_DATE
IS
    ARG_HOS_STATUS NUMBER;
BEGIN
 
    FOR i IN (SELECT HOS_STATUS FROM HOS_RESERVATION ) LOOP
    
    ARG_HOS_STATUS := i.HOS_STATUS;   
    
    IF ARG_HOS_STATUS = 0 THEN
         UPDATE HOS_RESERVATION SET HOS_STATUS = 3 WHERE HOS_DATE < SYSDATE AND HOS_STATUS = 0;
    ELSIF ARG_HOS_STATUS = 1 THEN 
     UPDATE HOS_RESERVATION SET HOS_STATUS = 2 WHERE HOS_DATE < SYSDATE AND HOS_STATUS = 1;
    END IF; 
    
    END LOOP;
    
    COMMIT;
END;